
import { GoogleGenAI } from "@google/genai";

// AI service for Ligi Kuu Pro.
// This service provides AI-powered features for match simulations, scheduling, and creative assets.

/**
 * Simulates a match result (Placeholder for future implementation).
 */
export const simulateMatchResult = async () => null;

/**
 * Generates a tournament schedule (Placeholder for future implementation).
 */
export const generateAISchedule = async () => null;

/**
 * Generates a cinematic descriptive prompt for a sports match poster.
 * @param homeName The name of the home team.
 * @param awayName The name of the away team.
 */
export const generateMatchPosterPrompt = async (homeName: string, awayName: string): Promise<string> => {
  // Fix: Added parameters (homeName, awayName) to resolve the "Expected 0 arguments, but got 2" error in PosterGenerator.tsx.
  // Implemented Gemini 3 Flash logic to generate a high-quality descriptive prompt.
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Create a cinematic and high-energy image generation prompt for a football match poster between ${homeName} and ${awayName}. Include details about stadium atmosphere, team colors, and dramatic lighting. Keep it under 70 words.`,
      config: {
        systemInstruction: "You are a professional sports media creative director. Output ONLY the descriptive prompt for an image generator. No additional conversation or quotes."
      }
    });
    return response.text || `Professional sports poster for ${homeName} vs ${awayName}, stadium lights, high energy, cinematic style.`;
  } catch (error) {
    console.error("Error generating match poster prompt:", error);
    return `Cinematic sports poster for ${homeName} vs ${awayName}, 8k, professional photography.`;
  }
};

/**
 * Generates a poster image based on a descriptive prompt.
 * @param prompt The descriptive prompt generated by generateMatchPosterPrompt.
 */
export const generatePosterImage = async (prompt: string): Promise<string | null> => {
  // Fix: Added parameter (prompt) to resolve the "Expected 0 arguments, but got 1" error in PosterGenerator.tsx.
  // Implemented Gemini 2.5 Flash Image logic to generate the actual image bytes.
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [{ text: prompt }]
      },
      config: {
        imageConfig: {
          aspectRatio: "16:9"
        }
      }
    });

    // Iterate through candidates and parts to find the inlineData image part as per guidelines.
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
      }
    }
    return null;
  } catch (error) {
    console.error("Error generating poster image:", error);
    return null;
  }
};
